// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'flutter_api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterMemberInfo`, `FlutterPusherEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Initialize logging for the Rust library
void initLogging({required String level}) =>
    RustLib.instance.api.crateFlutterApiInitLogging(level: level);

/// Get library version
String getVersion() => RustLib.instance.api.crateFlutterApiGetVersion();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterChannel>>
abstract class FlutterChannel implements RustOpaqueInterface {
  /// Get channel name
  String getName();

  /// Check if channel is subscribed
  bool isSubscribed();

  /// Trigger a client event (for private/presence channels)
  bool trigger({required String eventName, required String data});

  /// Unbind all events from this channel
  void unbindAll();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterSockudoClient>>
abstract class FlutterSockudoClient implements RustOpaqueInterface {
  /// Connect to the Pusher server
  Future<void> connect();

  /// Disconnect from the server
  void disconnect();

  /// Get delta compression statistics
  FlutterDeltaStats? getDeltaStats();

  /// Get socket ID
  String? getSocketId();

  /// Get current connection state
  String getState();

  /// Check if connected
  bool isConnected();

  /// Create a new Sockudo client
  factory FlutterSockudoClient({required FlutterPusherOptions options}) =>
      RustLib.instance.api
          .crateFlutterApiFlutterSockudoClientNew(options: options);

  /// Reset delta compression statistics
  void resetDeltaStats();

  /// Subscribe to a channel
  FlutterChannel subscribe({required String channelName});

  /// Unsubscribe from a channel
  void unsubscribe({required String channelName});
}

/// Delta compression statistics
@freezed
sealed class FlutterDeltaStats with _$FlutterDeltaStats {
  const factory FlutterDeltaStats({
    required BigInt totalMessages,
    required BigInt deltaMessages,
    required BigInt fullMessages,
    required BigInt totalBytesWithoutCompression,
    required BigInt totalBytesWithCompression,
    required double bandwidthSavedPercent,
    required BigInt errors,
  }) = _FlutterDeltaStats;
}

/// Pusher configuration options for Flutter
@freezed
sealed class FlutterPusherOptions with _$FlutterPusherOptions {
  const factory FlutterPusherOptions({
    required String appKey,
    String? cluster,
    String? wsHost,
    int? wsPort,
    bool? useTls,
    String? authEndpoint,
    BigInt? activityTimeoutMs,
    BigInt? pongTimeoutMs,
    BigInt? unavailableTimeoutMs,
    bool? enableDeltaCompression,
    bool? enableStats,
    bool? debug,
    String? userAuthEndpoint,
    bool? disableReconnection,
    int? maxReconnectionAttempts,
    BigInt? reconnectionDelayMs,
    BigInt? maxReconnectionDelayMs,
  }) = _FlutterPusherOptions;
}
