// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'flutter_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1454570309;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'sockudo_client',
    ioDirectory: '../target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateFlutterApiFlutterChannelGetName({required FlutterChannel that});

  bool crateFlutterApiFlutterChannelIsSubscribed(
      {required FlutterChannel that});

  bool crateFlutterApiFlutterChannelTrigger(
      {required FlutterChannel that,
      required String eventName,
      required String data});

  void crateFlutterApiFlutterChannelUnbindAll({required FlutterChannel that});

  Future<void> crateFlutterApiFlutterSockudoClientConnect(
      {required FlutterSockudoClient that});

  void crateFlutterApiFlutterSockudoClientDisconnect(
      {required FlutterSockudoClient that});

  FlutterDeltaStats? crateFlutterApiFlutterSockudoClientGetDeltaStats(
      {required FlutterSockudoClient that});

  String? crateFlutterApiFlutterSockudoClientGetSocketId(
      {required FlutterSockudoClient that});

  String crateFlutterApiFlutterSockudoClientGetState(
      {required FlutterSockudoClient that});

  bool crateFlutterApiFlutterSockudoClientIsConnected(
      {required FlutterSockudoClient that});

  FlutterSockudoClient crateFlutterApiFlutterSockudoClientNew(
      {required FlutterPusherOptions options});

  void crateFlutterApiFlutterSockudoClientResetDeltaStats(
      {required FlutterSockudoClient that});

  FlutterChannel crateFlutterApiFlutterSockudoClientSubscribe(
      {required FlutterSockudoClient that, required String channelName});

  void crateFlutterApiFlutterSockudoClientUnsubscribe(
      {required FlutterSockudoClient that, required String channelName});

  String crateFlutterApiGetVersion();

  void crateFlutterApiInitLogging({required String level});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FlutterChannel;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FlutterChannel;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FlutterChannelPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FlutterSockudoClient;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FlutterSockudoClient;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FlutterSockudoClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateFlutterApiFlutterChannelGetName({required FlutterChannel that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterChannelGetNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterChannelGetNameConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterChannel_get_name",
        argNames: ["that"],
      );

  @override
  bool crateFlutterApiFlutterChannelIsSubscribed(
      {required FlutterChannel that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterChannelIsSubscribedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterChannelIsSubscribedConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterChannel_is_subscribed",
        argNames: ["that"],
      );

  @override
  bool crateFlutterApiFlutterChannelTrigger(
      {required FlutterChannel that,
      required String eventName,
      required String data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
            that, serializer);
        sse_encode_String(eventName, serializer);
        sse_encode_String(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateFlutterApiFlutterChannelTriggerConstMeta,
      argValues: [that, eventName, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterChannelTriggerConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterChannel_trigger",
        argNames: ["that", "eventName", "data"],
      );

  @override
  void crateFlutterApiFlutterChannelUnbindAll({required FlutterChannel that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterChannelUnbindAllConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterChannelUnbindAllConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterChannel_unbind_all",
        argNames: ["that"],
      );

  @override
  Future<void> crateFlutterApiFlutterSockudoClientConnect(
      {required FlutterSockudoClient that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientConnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_connect",
        argNames: ["that"],
      );

  @override
  void crateFlutterApiFlutterSockudoClientDisconnect(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientDisconnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_disconnect",
        argNames: ["that"],
      );

  @override
  FlutterDeltaStats? crateFlutterApiFlutterSockudoClientGetDeltaStats(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_flutter_delta_stats,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientGetDeltaStatsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateFlutterApiFlutterSockudoClientGetDeltaStatsConstMeta =>
          const TaskConstMeta(
            debugName: "FlutterSockudoClient_get_delta_stats",
            argNames: ["that"],
          );

  @override
  String? crateFlutterApiFlutterSockudoClientGetSocketId(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientGetSocketIdConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientGetSocketIdConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_get_socket_id",
        argNames: ["that"],
      );

  @override
  String crateFlutterApiFlutterSockudoClientGetState(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientGetStateConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientGetStateConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_get_state",
        argNames: ["that"],
      );

  @override
  bool crateFlutterApiFlutterSockudoClientIsConnected(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientIsConnectedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientIsConnectedConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_is_connected",
        argNames: ["that"],
      );

  @override
  FlutterSockudoClient crateFlutterApiFlutterSockudoClientNew(
      {required FlutterPusherOptions options}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_flutter_pusher_options(options, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientNewConstMeta,
      argValues: [options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_new",
        argNames: ["options"],
      );

  @override
  void crateFlutterApiFlutterSockudoClientResetDeltaStats(
      {required FlutterSockudoClient that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientResetDeltaStatsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateFlutterApiFlutterSockudoClientResetDeltaStatsConstMeta =>
          const TaskConstMeta(
            debugName: "FlutterSockudoClient_reset_delta_stats",
            argNames: ["that"],
          );

  @override
  FlutterChannel crateFlutterApiFlutterSockudoClientSubscribe(
      {required FlutterSockudoClient that, required String channelName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        sse_encode_String(channelName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientSubscribeConstMeta,
      argValues: [that, channelName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_subscribe",
        argNames: ["that", "channelName"],
      );

  @override
  void crateFlutterApiFlutterSockudoClientUnsubscribe(
      {required FlutterSockudoClient that, required String channelName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
            that, serializer);
        sse_encode_String(channelName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiFlutterSockudoClientUnsubscribeConstMeta,
      argValues: [that, channelName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiFlutterSockudoClientUnsubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterSockudoClient_unsubscribe",
        argNames: ["that", "channelName"],
      );

  @override
  String crateFlutterApiGetVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiGetVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiGetVersionConstMeta => const TaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  @override
  void crateFlutterApiInitLogging({required String level}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(level, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiInitLoggingConstMeta,
      argValues: [level],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiInitLoggingConstMeta => const TaskConstMeta(
        debugName: "init_logging",
        argNames: ["level"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FlutterChannel => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FlutterChannel => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FlutterSockudoClient => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FlutterSockudoClient => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FlutterChannel
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterSockudoClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterChannel
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterSockudoClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterChannel
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterSockudoClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterDeltaStats dco_decode_box_autoadd_flutter_delta_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_delta_stats(raw);
  }

  @protected
  FlutterPusherOptions dco_decode_box_autoadd_flutter_pusher_options(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_pusher_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FlutterDeltaStats dco_decode_flutter_delta_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FlutterDeltaStats(
      totalMessages: dco_decode_u_64(arr[0]),
      deltaMessages: dco_decode_u_64(arr[1]),
      fullMessages: dco_decode_u_64(arr[2]),
      totalBytesWithoutCompression: dco_decode_u_64(arr[3]),
      totalBytesWithCompression: dco_decode_u_64(arr[4]),
      bandwidthSavedPercent: dco_decode_f_64(arr[5]),
      errors: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  FlutterPusherOptions dco_decode_flutter_pusher_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return FlutterPusherOptions(
      appKey: dco_decode_String(arr[0]),
      cluster: dco_decode_opt_String(arr[1]),
      wsHost: dco_decode_opt_String(arr[2]),
      wsPort: dco_decode_opt_box_autoadd_u_16(arr[3]),
      useTls: dco_decode_opt_box_autoadd_bool(arr[4]),
      authEndpoint: dco_decode_opt_String(arr[5]),
      activityTimeoutMs: dco_decode_opt_box_autoadd_u_64(arr[6]),
      pongTimeoutMs: dco_decode_opt_box_autoadd_u_64(arr[7]),
      unavailableTimeoutMs: dco_decode_opt_box_autoadd_u_64(arr[8]),
      enableDeltaCompression: dco_decode_opt_box_autoadd_bool(arr[9]),
      enableStats: dco_decode_opt_box_autoadd_bool(arr[10]),
      debug: dco_decode_opt_box_autoadd_bool(arr[11]),
      userAuthEndpoint: dco_decode_opt_String(arr[12]),
      disableReconnection: dco_decode_opt_box_autoadd_bool(arr[13]),
      maxReconnectionAttempts: dco_decode_opt_box_autoadd_u_32(arr[14]),
      reconnectionDelayMs: dco_decode_opt_box_autoadd_u_64(arr[15]),
      maxReconnectionDelayMs: dco_decode_opt_box_autoadd_u_64(arr[16]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  FlutterDeltaStats? dco_decode_opt_box_autoadd_flutter_delta_stats(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_flutter_delta_stats(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  FlutterChannel
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FlutterSockudoClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FlutterChannel
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FlutterSockudoClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FlutterChannel
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterChannelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FlutterSockudoClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterSockudoClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  FlutterDeltaStats sse_decode_box_autoadd_flutter_delta_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_delta_stats(deserializer));
  }

  @protected
  FlutterPusherOptions sse_decode_box_autoadd_flutter_pusher_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_pusher_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FlutterDeltaStats sse_decode_flutter_delta_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalMessages = sse_decode_u_64(deserializer);
    var var_deltaMessages = sse_decode_u_64(deserializer);
    var var_fullMessages = sse_decode_u_64(deserializer);
    var var_totalBytesWithoutCompression = sse_decode_u_64(deserializer);
    var var_totalBytesWithCompression = sse_decode_u_64(deserializer);
    var var_bandwidthSavedPercent = sse_decode_f_64(deserializer);
    var var_errors = sse_decode_u_64(deserializer);
    return FlutterDeltaStats(
        totalMessages: var_totalMessages,
        deltaMessages: var_deltaMessages,
        fullMessages: var_fullMessages,
        totalBytesWithoutCompression: var_totalBytesWithoutCompression,
        totalBytesWithCompression: var_totalBytesWithCompression,
        bandwidthSavedPercent: var_bandwidthSavedPercent,
        errors: var_errors);
  }

  @protected
  FlutterPusherOptions sse_decode_flutter_pusher_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appKey = sse_decode_String(deserializer);
    var var_cluster = sse_decode_opt_String(deserializer);
    var var_wsHost = sse_decode_opt_String(deserializer);
    var var_wsPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_useTls = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_authEndpoint = sse_decode_opt_String(deserializer);
    var var_activityTimeoutMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_pongTimeoutMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_unavailableTimeoutMs =
        sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_enableDeltaCompression =
        sse_decode_opt_box_autoadd_bool(deserializer);
    var var_enableStats = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_debug = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_userAuthEndpoint = sse_decode_opt_String(deserializer);
    var var_disableReconnection = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_maxReconnectionAttempts =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_reconnectionDelayMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_maxReconnectionDelayMs =
        sse_decode_opt_box_autoadd_u_64(deserializer);
    return FlutterPusherOptions(
        appKey: var_appKey,
        cluster: var_cluster,
        wsHost: var_wsHost,
        wsPort: var_wsPort,
        useTls: var_useTls,
        authEndpoint: var_authEndpoint,
        activityTimeoutMs: var_activityTimeoutMs,
        pongTimeoutMs: var_pongTimeoutMs,
        unavailableTimeoutMs: var_unavailableTimeoutMs,
        enableDeltaCompression: var_enableDeltaCompression,
        enableStats: var_enableStats,
        debug: var_debug,
        userAuthEndpoint: var_userAuthEndpoint,
        disableReconnection: var_disableReconnection,
        maxReconnectionAttempts: var_maxReconnectionAttempts,
        reconnectionDelayMs: var_reconnectionDelayMs,
        maxReconnectionDelayMs: var_maxReconnectionDelayMs);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FlutterDeltaStats? sse_decode_opt_box_autoadd_flutter_delta_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flutter_delta_stats(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          FlutterChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterChannelImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          FlutterSockudoClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterSockudoClientImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          FlutterChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterChannelImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          FlutterSockudoClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterSockudoClientImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterChannel(
          FlutterChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterChannelImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterSockudoClient(
          FlutterSockudoClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FlutterSockudoClientImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_delta_stats(
      FlutterDeltaStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_delta_stats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_pusher_options(
      FlutterPusherOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_pusher_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_flutter_delta_stats(
      FlutterDeltaStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalMessages, serializer);
    sse_encode_u_64(self.deltaMessages, serializer);
    sse_encode_u_64(self.fullMessages, serializer);
    sse_encode_u_64(self.totalBytesWithoutCompression, serializer);
    sse_encode_u_64(self.totalBytesWithCompression, serializer);
    sse_encode_f_64(self.bandwidthSavedPercent, serializer);
    sse_encode_u_64(self.errors, serializer);
  }

  @protected
  void sse_encode_flutter_pusher_options(
      FlutterPusherOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appKey, serializer);
    sse_encode_opt_String(self.cluster, serializer);
    sse_encode_opt_String(self.wsHost, serializer);
    sse_encode_opt_box_autoadd_u_16(self.wsPort, serializer);
    sse_encode_opt_box_autoadd_bool(self.useTls, serializer);
    sse_encode_opt_String(self.authEndpoint, serializer);
    sse_encode_opt_box_autoadd_u_64(self.activityTimeoutMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.pongTimeoutMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.unavailableTimeoutMs, serializer);
    sse_encode_opt_box_autoadd_bool(self.enableDeltaCompression, serializer);
    sse_encode_opt_box_autoadd_bool(self.enableStats, serializer);
    sse_encode_opt_box_autoadd_bool(self.debug, serializer);
    sse_encode_opt_String(self.userAuthEndpoint, serializer);
    sse_encode_opt_box_autoadd_bool(self.disableReconnection, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxReconnectionAttempts, serializer);
    sse_encode_opt_box_autoadd_u_64(self.reconnectionDelayMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.maxReconnectionDelayMs, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flutter_delta_stats(
      FlutterDeltaStats? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flutter_delta_stats(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class FlutterChannelImpl extends RustOpaque implements FlutterChannel {
  // Not to be used by end users
  FlutterChannelImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FlutterChannelImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FlutterChannel,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterChannel,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterChannelPtr,
  );

  /// Get channel name
  String getName() => RustLib.instance.api.crateFlutterApiFlutterChannelGetName(
        that: this,
      );

  /// Check if channel is subscribed
  bool isSubscribed() =>
      RustLib.instance.api.crateFlutterApiFlutterChannelIsSubscribed(
        that: this,
      );

  /// Trigger a client event (for private/presence channels)
  bool trigger({required String eventName, required String data}) =>
      RustLib.instance.api.crateFlutterApiFlutterChannelTrigger(
          that: this, eventName: eventName, data: data);

  /// Unbind all events from this channel
  void unbindAll() =>
      RustLib.instance.api.crateFlutterApiFlutterChannelUnbindAll(
        that: this,
      );
}

@sealed
class FlutterSockudoClientImpl extends RustOpaque
    implements FlutterSockudoClient {
  // Not to be used by end users
  FlutterSockudoClientImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FlutterSockudoClientImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_FlutterSockudoClient,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_FlutterSockudoClient,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_FlutterSockudoClientPtr,
  );

  /// Connect to the Pusher server
  Future<void> connect() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientConnect(
        that: this,
      );

  /// Disconnect from the server
  void disconnect() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientDisconnect(
        that: this,
      );

  /// Get delta compression statistics
  FlutterDeltaStats? getDeltaStats() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientGetDeltaStats(
        that: this,
      );

  /// Get socket ID
  String? getSocketId() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientGetSocketId(
        that: this,
      );

  /// Get current connection state
  String getState() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientGetState(
        that: this,
      );

  /// Check if connected
  bool isConnected() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientIsConnected(
        that: this,
      );

  /// Reset delta compression statistics
  void resetDeltaStats() =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientResetDeltaStats(
        that: this,
      );

  /// Subscribe to a channel
  FlutterChannel subscribe({required String channelName}) =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientSubscribe(
          that: this, channelName: channelName);

  /// Unsubscribe from a channel
  void unsubscribe({required String channelName}) =>
      RustLib.instance.api.crateFlutterApiFlutterSockudoClientUnsubscribe(
          that: this, channelName: channelName);
}
