/// Sockudo Client - Flutter bindings
///
/// A high-performance Pusher-compatible WebSocket client for Flutter.
library sockudo_client;

// Export the generated bindings
// These will be generated by flutter_rust_bridge
export 'src/bridge_generated.dart';

// Export convenience classes
export 'src/sockudo_client.dart';
